plugins { id 'com.android.application' }

android {
    namespace 'com.amhdesign.pointercustomizer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.amhdesign.pointercustomizer'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }

    buildFeatures {
        aidl true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation "dev.rikka.shizuku:api:13.1.5"
    implementation "dev.rikka.shizuku:provider:13.1.5"
}